### ISSUE TITLE
Installation error 'tr1/random' file not found

### ISSUE THREAD

**Issue by maxneal** [Chrom3D/Chrom3D#1]
Hello - Following the installation instructions, I tried to install Chrom3D on a Mac running 10.11.5 but I got some errors, and the binary wasn't created. The first error message was

> In file included from src/Util.cpp:1:
> src/Util.h:10:14: fatal error: 'tr1/random' file not found
>     #include <tr1/random>

The other error messages are similar, all complaining about 'tr1/random' not being found. Here's the full output after running the "make" command:

> 
> 
> g++ -O3 -I src/tclap-1.2.1/include src/Util.cpp src/Bead.cpp src/Chromosome.cpp src/Randomizer.cpp src/Constraint.cpp src/Model.cpp src/MCMC.cpp src/Chrom3D.cpp -o Chrom3D
> In file included from src/Util.cpp:1:
> src/Util.h:10:14: fatal error: 'tr1/random' file not found
>     #include <tr1/random>
>              ^
> 1 error generated.
> In file included from src/Bead.cpp:1:
> In file included from src/Bead.h:7:
> src/Util.h:10:14: fatal error: 'tr1/random' file not found
>     #include <tr1/random>
>              ^
> 1 error generated.
> In file included from src/Chromosome.cpp:1:
> In file included from src/Chromosome.h:11:
> src/Util.h:10:14: fatal error: 'tr1/random' file not found
>     #include <tr1/random>
>              ^
> 1 error generated.
> In file included from src/Randomizer.cpp:1:
> In file included from src/Randomizer.h:4:
> In file included from src/Chromosome.h:11:
> src/Util.h:10:14: fatal error: 'tr1/random' file not found
>     #include <tr1/random>
>              ^
> 1 error generated.
> In file included from src/Constraint.cpp:1:
> In file included from src/Constraint.h:5:
> In file included from src/Bead.h:7:
> src/Util.h:10:14: fatal error: 'tr1/random' file not found
>     #include <tr1/random>
>              ^
> 1 error generated.
> In file included from src/Model.cpp:1:
> In file included from src/Model.h:5:
> In file included from src/Chromosome.h:11:
> src/Util.h:10:14: fatal error: 'tr1/random' file not found
>     #include <tr1/random>
>              ^
> 1 error generated.
> In file included from src/MCMC.cpp:1:
> In file included from src/MCMC.h:3:
> In file included from src/Model.h:5:
> In file included from src/Chromosome.h:11:
> src/Util.h:10:14: fatal error: 'tr1/random' file not found
>     #include <tr1/random>
>              ^
> 1 error generated.
> In file included from src/Chrom3D.cpp:2:
> src/../src/Util.h:10:14: fatal error: 'tr1/random' file not found
>     #include <tr1/random>
>              ^
> 1 error generated.
> make: *** [all] Error 1

Thanks very much in advance for your help.

**Comment by maxneal** [comment]
I seem to have gotten past this error by changing line 10 of src/Util.h to     
`#include <tr1/random.hpp>
`

(i.e. by adding the ".hpp" extension)

**Comment by monikasekelja** [comment]
Thanks for reporting back how you solved it. Which compiler version did you use?

**Comment by maxneal** [comment]
Here's the output I get from 'g++ -v':

Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
