### ISSUE TITLE
Chromosome number question

### ISSUE THREAD

**Issue by al614** [Chrom3D/Chrom3D#13]
hi!

 from the output, it looks like i am dealing with 23 chromosomes,

# Rescaled bead sizes from 61.128 to 0.15
# chromosomes: 23
# beads: 7641
# interactions: 345

but in reality, i am only working on one chromosome. is this still okay and will this produce a model of just one chromosome?

Thank you

**Comment by jonnings** [comment]
The output indicates that your GTrack file contains 23 different chromosomes. The resulting model will therefore also consist of 23 chromosomes. If you are only interested in modeling a single chromosome, you should remove the other 22 chromosomes from the GTrack file and proceed with local modeling as  discussed in Box 5 in [our recent Nature Protocols article](https://rdcu.be/MFiG).
