### ISSUE TITLE
Sex chromosomes on chrom3D

### ISSUE THREAD

**Issue by sespesogil** [Chrom3D/Chrom3D#14]
Hi! 

I am a bit puzzled about the sex chromosomes. As I commented before I am implementing your tool in mouse and so far so good. Although for female mouse I needed to trick the chromosome size files. Anyway.... my question is...how do you deal with this? Because there is no real option in your program to choose different sex and literally your makediploid.sh script doubles the lines. Please correct me if I am wrong, but I need a hand on this. Also really pleased to help on this if needed. I have tricked that by changing the chromosome sizes files, but not sure if that is totally ok. 

I also implemented a wrapper of your tool to be run in a faster way, welcome to use/change it. Still a bit beta though. Working on it.  

Thanks a lot!!

**Comment by sespesogil** [comment]
Please realize for instance if you have a male mouse HiC dataset, your make_diploid script will produce at the end 2 chromosomes X and 2 chromosomes Y.  Am I right?

**Comment by jonnings** [comment]
Hi, sespesogil

As you correctly have noticed, the make_diploid_gtrack.py script simply creates an extra copy of each chromosome in the GTrack file. As you can imagine, in almost all circumstances dealing with other species, cell lines, assemblies etc., you will have to modify this script according to the particular assembly you are working with.
