### ISSUE TITLE
NCHG interchromosomal running problem

### ISSUE THREAD

**Issue by sespesogil** [Chrom3D/Chrom3D#15]
Hi, 

I have realized that for some datasets when running NCHG there are not significant interchromosomal interactions called. The error that I get is: 

NCHG: CCCsig/CCCStatistics.cpp:323: double getCumulativeNCHG(int, int, int, int, double, double, bool): Assertion `xmean >= x1' failed.

Any recommendations?

**Comment by jonnings** [comment]
Hi. Do you have an input dataset (or a minimal example) that reproduces the error?

**Comment by sespesogil** [comment]
Hi, yes. Here the bedpe of interchromosomal at 1MB, let me know if you need something else. 

[07_01_19_IMR90.1MBres.inter.bedpe.gz](https://github.com/Chrom3D/Chrom3D/files/3355519/07_01_19_IMR90.1MBres.inter.bedpe.gz)

Thanks!

**Comment by jonnings** [comment]
I can confirm that the dataset you provide does cause the assertion to fail. The problem seems to be caused by issues with floating point precision in cases where the marginals are very small compared to the total number of interactions for a chromosome. I am working on a fix, so please stay tuned.

**Comment by jonnings** [comment]
Hi, again @sespesogil. Please find an updated version of NCHG [here](http://folk.uio.no/jonaspau/hic/NCHG_hic_v2.zip). This version uses the Boost Hypergeometric distribution, but if you are able to compile and run Chrom3D, then this should compile as well.
Please let me know if this solves your problem.

**Comment by sespesogil** [comment]
Thanks! I will try and update you

**Comment by sespesogil** [comment]
Sorry @jonnings  the link you provided is broken.  Can you provide a new one?

**Comment by jonnings** [comment]
Sorry, @sespesogil, try again now!

**Comment by sespesogil** [comment]
Yup, now is producing an output at least. I have tried to run Chrom3D but I get the error:

Assertion 'min arg<=max_arg' failed 
[07_08_19_IMR90_bonferroni05.inter_intra.diploid.gtrack.gz](https://github.com/Chrom3D/Chrom3D/files/3370058/07_08_19_IMR90_bonferroni05.inter_intra.diploid.gtrack.gz)

That happened to me when there is chromosomes with low number of beads, concerning basically chrY. Not sure now, I need to check. When this happens, what do you suggest? 

Thanks a lot!!!

**Comment by jonnings** [comment]
Hi again, @sespesogil. The failed assertion seems to come from chr1_A and chr1_B in your uploaded GTrack file. These seem to be defined as a single, huge bead covering the entire chromosome:  
`chr1_A	0	248956422	chr1_A:0-248956422`

Chrom3D will definitively fail if a chromosome is defined by fewer than 3 beads.

**Comment by sespesogil** [comment]
Makes sense. Thanks @jonnings ! This is directly related with the data sparsity, I will rerun Arrowhead with a different resolution to see if gets better. 


Thanks a lot again! Help was really useful!
