### ISSUE TITLE
Error in Model::getLossScore()

### ISSUE THREAD

**Issue by SamPIngram** [Chrom3D/Chrom3D#16]
Hi,

I really like your package. I think you may not be counting INTERACTION_INTER constraints when you call Model::getLossScore(). It shouldn't really change your results. However, I thought I would mention it. On line 202 and line 222 of model.cc, you have a logic statement, in which the last or piece is not appropriately queried. 

`if(constraintType == "INTERACTION" || constraintType == "INTERACTION_DIST" || constraintType == "INTERACTION_INTRA" || "INTERACTION_INTER"){}`

Unless I am mistaken, should be:

``if(constraintType == "INTERACTION" || constraintType == "INTERACTION_DIST" || constraintType == "INTERACTION_INTRA" || constraintType == "INTERACTION_INTER"){}``

If I am mistaken, I do apologise. Otherwise, I hope this is helpful. 
Sam

**Comment by jonnings** [comment]
Thanks for reporting this! This has now been fixed.
