### ISSUE TITLE
No coordinate of TADs generated by Chrom3D

### ISSUE THREAD

**Issue by Qi-Yang-Bioinfo** [Chrom3D/Chrom3D#17]
![Annotation 2019-12-03 150649](https://user-images.githubusercontent.com/10727217/70028180-e826c780-15de-11ea-87ab-83eebdfd8ee2.png)
![Annotation 2019-12-03 150821](https://user-images.githubusercontent.com/10727217/70028181-e8bf5e00-15de-11ea-8bfa-0bb62fe11090.png)
This is a seemingly normal gtrack file, Chrom3D runs without error, but there is no coordinate in the .cmm file, coordinates are NAN.
I followed steps in the pipeline with some modifications that I used insulation score to call TADs.

**Comment by Qi-Yang-Bioinfo** [comment]
I use 50kb for intra and 1mb for inter as recommended.
on non-diploid human Hi-C data.
And it takes really long time to run on a 2mb gtrack file(about 10 hours).

**Comment by jonnings** [comment]
Could you share (parts of) your gtrack file? I would like to try and reproduce the problem on my side to see what the issue really is.

**Comment by Qi-Yang-Bioinfo** [comment]
> Could you share (parts of) your gtrack file? I would like to try and reproduce the problem on my side to see what the issue really is.



[sample.zip](https://github.com/Chrom3D/Chrom3D/files/3921027/sample.zip)
Thanks for the reply, here is the gtrack cmm file.

**Comment by jonnings** [comment]
Thanks, @IPOI. I do not know exactly which Chrom3D command you ran, but I assume you used the  `-y`  parameter (e.g. `-y 0.15`). It seems to me that the problem you are experiencing comes from the tiny beads that you have defined, that cover a single basepair only. There are a total of 4030 of those in your provided gtrack file.
When I simply remove these (they do not seem to interact with anything):
`awk '($3-$2)!=1'  sample_inter_intra.gtrack > sample_inter_intra_nosinglebp.gtrack`
and rerun on the _sample_inter_intra_nosinglebp.gtrack_ file, the simulation will be a lot faster and the problem with nan x,y,z coordinates seems to be fixed.

Chrom3D is not really designed to tackle 1bp beads. Unless they are there for a really good reason, I suggest removing them. If you decide to do this, you probably want to redefine the start and end coordinates accordingly, to get a complete genomic coverage of you beads. Chrom3D will actually not care whether or not your beads completely cover a chromosome, and will put consecutive beads next to each other regardless of possible gaps in the coordinates. But, for hassle-free downstream analysis of the 3D structures/beads, it will probably be good to have a complete genomic coverage of the beads.

**Comment by Qi-Yang-Bioinfo** [comment]
I check the temp files generated in the pipeline.
These 1bp segments first appeared in the per chromosome domain files.
![image](https://user-images.githubusercontent.com/10727217/70211081-39fe5780-176f-11ea-9869-9794e648773b.png)
 
In my workflow, I used the insulation score as TAD caller. TAD boundaries are stitched into consecutive "Juicer" like domains by my own script.

On the first attempt, I stitched the domains in an end-to-end manner(start of a domain is the same as the end of the previous domain), but the script **arrowhead_to_domains.sh** merged all domains on a chromosome. After checking this script, I realized that I can't have domains in an end-to-end manner to avoid this, so I add 1 to the start point of each domain. 

After that, **arrowhead_to_domains.sh** will fill these 1bp with gaps. I don't know how the rest of the pipeline will treat these gaps.

Results are normal now, as I removed these 1bp gaps.

Are they not supposed to exist in the gtrack file?  Or are they allowed but has to be about the same size as domains in the gtrack file? Can you further explain what gaps will do to my structure, are gaps size reflected in distance between beads?

Thanks for your patience and quick reply.
