### ISSUE TITLE
example to run chrom3D on Hi-C data and lamin ChIP-seq file

### ISSUE THREAD

**Issue by ahmedabbas81** [Chrom3D/Chrom3D#19]
Hello,

Is there an example to illustrate how to run chrom3D on Hi-C and lamin ChIP-seq.

I want to calculate the structure of all chromosomes of GM12878 (whole genome)

Thank you

**Comment by jonnings** [comment]
Hi @ahmedabbas81. Yes, there is an example at https://github.com/Chrom3D/pipeline and a detailed description of various Chrom3D use cases published here: https://www.nature.com/articles/nprot.2018.009/boxes/bx1

**Comment by ahmedabbas81** [comment]
Hello,

It is giving me this error:

Header is missing in the GTrack file

Here is the header I have

```
##gtrack version: 1.0
##track type: linked segments
###seqid	start	end	id	radius	edges
chr1_A	0	249250621	chr1_A:0-249250621
chr1_B	0	249250621	chr1_B:0-249250621
chr1_A	0	249250621	chr1_A:0-249250621	1	chr9_A:0-141213431;chr8_A:0-146364022;chr5_A:0-180915260;chr3_A:0-198022430;chr4_A:0-191154276;chr6_A:0-171115067;chr2_A:0-243199373;chr7_A:0-159138663
chr1_B	0	249250621	chr1_B:0-249250621	1	chr9_B:0-141213431;chr8_B:0-146364022;chr5_B:0-180915260;chr3_B:0-198022430;chr4_B:0-191154276;chr6_B:0-171115067;chr2_B:0-243199373;chr7_B:0-159138663
chr1_A	0	915000	chr1_A:0-915000
chr1_B	0	915000	chr1_B:0-915000
chr1_A	0	915000	chr1_A:0-915000	1	chr1_A:915000-1005000;chr1_A:1030000-1235000
```

Thank you

**Comment by jonnings** [comment]
The error is due to missing data/information in line 1,2,5 and 6 in the 'radius' and 'edges' column.

**Comment by ahmedabbas81** [comment]
How can I solve it? I followed the steps exactly. Thank you

**Comment by jonnings** [comment]
Could you provide a file/list containing all the steps you have run?

**Comment by ahmedabbas81** [comment]
I believe the problem in adding the inter chromosomal constraints

When I use python2, it does not find pybedtools module

And to use python3, I need to change "inter_chrom_beads.py", and it seems I am making something wrong, so it writes the same line twice. One time without edge and radius and the second time with them. 

Is there a chance to send me a version for inter_chrom_beads.py only that works on python3 please? It should be very minor changes but it seems I did it wrong.

If not, I will try to install python 2 again

Thank you

**Comment by ahmedabbas81** [comment]
The program is running since 22 hours. It did not finish yet. Is that normal? It is for the 3D genome of GM12878. I thought it takes 15 hours only.

Thank you
