### ISSUE TITLE
beads for whole chromosomes

### ISSUE THREAD

**Issue by ahmedabbas81** [Chrom3D/Chrom3D#22]
Hello,

I have in the output structure beads representing whole chromosomes, in addition to beads representing TADs. Is that expected or I should repeat the analysis again and try to correct any mistake?
I hope to get an answer so that I do not repeat the work if not needed.
Thanks

**Comment by ahmedabbas81** [comment]
I ran the program again and gave me the same gtrack file
here it its first few lines

does it look correct? Especially the line in bold

Thank you

##gtrack version: 1.0
##track type: linked segments
###seqid	start	end	id	radius	edges
**chr1	0	249250621	chr1:0-249250621	1	chr5:0-180915260;chr8:0-146364022;chr6:0-171115067;chr4:0-191154276;chr2:0-243199373;chr9:0-141213431;chr3:0-198022430;chr7:0-159138663**
chr1	0	915000	chr1:0-915000	1	chr1:915000-1005000;chr1:1030000-1235000
chr1	915000	1005000	chr1:915000-1005000	1	chr1:0-915000;chr1:1030000-1235000;chr1:156045000-156305000

**Comment by ahmedabbas81** [comment]
Any answer please? Thank you

**Comment by jonnings** [comment]
Sorry for my late reply, @ahmedabbas81 
Beads covering entire chromosomes are not expected, and indicate that something has gone wrong. Could you share the code and (parts of the) data generating the TADs/domains that you use for defining the beads?

**Comment by ahmedabbas81** [comment]
Thanks for answering

I am working with GM12878 cell line

I am using the TADs in https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE63525

I am attaching the TADs file

Thanks
[GSE63525_GM12878_primary+replicate_Arrowhead_domainlist.txt](https://github.com/Chrom3D/Chrom3D/files/4981261/GSE63525_GM12878_primary%2Breplicate_Arrowhead_domainlist.txt)

**Comment by jonnings** [comment]
Are you sure you managed to run `arrowhead_to_domains.sh` properly, as described [here](https://github.com/Chrom3D/pipeline#aggregation-of-hi-c-contact-counts-for-all-pairs-of-tads)?

When I run `arrowhead_to_domains.sh` on your provided _domainlist.txt file, the resulting .domains files look correct, without beads covering entire chromosomes:
![image](https://user-images.githubusercontent.com/5373069/88637923-12238180-d0bb-11ea-9cb6-fc9c5c0b9ded.png)

**Comment by ahmedabbas81** [comment]
yes, i get the same as you. Is this the only possibility for the appearance of beads covering all chromosome. By the way, when I tried IMR90, I did not get beads with entire chromosomes.

Thank you

![image](https://user-images.githubusercontent.com/32098502/88687180-f2458b00-d0c5-11ea-8ede-6b6c31a477f3.png)

**Comment by jonnings** [comment]
It is not the only possibility. But then we have at least ruled out that the problem started there. Could you look at the intermediate files to determine in which stem the whole-chromosome bead occurs?

**Comment by ahmedabbas81** [comment]
I believe that it appears for the first time in the intra-chromosome gtrack file

here are the first few lines


```
##gtrack version: 1.0
##track type: linked segments
###seqid	start	end	id	radius	edges
chr1	0	249250621	chr1:0-249250621	1	.
chr1	0	915000	chr1:0-915000	1	chr1:915000-1005000;chr1:1030000-1235000
chr1	915000	1005000	chr1:915000-1005000	1	chr1:0-915000;chr1:1030000-1235000;chr1:156045000-156305000
chr1	1005000	1030000	chr1:1005000-1030000	1	.
chr1	1030000	1235000	chr1:1030000-1235000	1	chr1:0-915000;chr1:915000-1005000;chr1:1235000-1255000;chr1:1255000-1450000;chr1:150335000-151145000;chr1:153625000-153965000;chr1:154315000-155145000;chr1:155145000-155215000;chr1:155215000-155570000;chr1:155825000-156040000;chr1:156045000-156305000;chr1:156310000-156870000
chr1	1235000	1255000	chr1:1235000-1255000	1	chr1:1030000-1235000;chr1:1255000-1450000;chr1:153625000-153965000;chr1:155145000-155215000;chr1:155825000-156040000;chr1:156045000-156305000
```

Thanks
