### ISSUE TITLE
issue with 'make'

### ISSUE THREAD

**Issue by nicky179854** [Chrom3D/Chrom3D#3]
I couldn't get 'make' to work even when adding my boost directory into the Makefile.

My Makefile looks like this:
##########################################################################
CFLAGS = -O3
SRCPATH=src
TCLAPINCLUDE=src/tclap-1.2.1/include

all:
	g++ -O3 -I /usr/include/boost -I $(TCLAPINCLUDE) $(SRCPATH)/Util.cpp $(SRCPATH)/Bead.cpp $(SRCPATH)/Chromosome.cpp $(SRCPATH)/Randomizer.cpp $(SRCPATH)/Constraint.cpp $(SRCPATH)/Model.cpp $(SRCPATH)/MCMC.cpp $(SRCPATH)/Chrom3D.cpp -o Chrom3D
##########################################################################

I've even tried getting rid of the -03 and placing it before the second '-I' and none of those tries worked.
Every time, I get tons of output saying "undefined references to" XXX. 

Here is the tail end of the output from running make:
##########################################################################
/tmp/ccU22FxL.o:(.rodata._ZTIN5TCLAP7CmdLineE[_ZTIN5TCLAP7CmdLineE]+0x0): undefined reference to `vtable for __cxxabiv1::__si_class_type_info'
/tmp/ccU22FxL.o:(.rodata._ZTIN5TCLAP8ValueArgISsEE[_ZTIN5TCLAP8ValueArgISsEE]+0x0): undefined reference to `vtable for __cxxabiv1::__si_class_type_info'
/tmp/ccU22FxL.o:(.rodata._ZTIN5TCLAP17UnlabeledValueArgISsEE[_ZTIN5TCLAP17UnlabeledValueArgISsEE]+0x0): more undefined references to `vtable for __cxxabiv1::__si_class_type_info' follow
/tmp/ccU22FxL.o:(.rodata._ZTIN5TCLAP10ConstraintISsEE[_ZTIN5TCLAP10ConstraintISsEE]+0x0): undefined reference to `vtable for __cxxabiv1::__class_type_info'
/tmp/ccU22FxL.o:(.rodata._ZTIN5TCLAP16ValuesConstraintISsEE[_ZTIN5TCLAP16ValuesConstraintISsEE]+0x0): undefined reference to `vtable for __cxxabiv1::__si_class_type_info'
/tmp/ccU22FxL.o:(.rodata._ZTIN5TCLAP8MultiArgISsEE[_ZTIN5TCLAP8MultiArgISsEE]+0x0): undefined reference to `vtable for __cxxabiv1::__si_class_type_info'
/tmp/ccU22FxL.o:(.rodata._ZTVN5TCLAP3ArgE[_ZTVN5TCLAP3ArgE]+0x28): undefined reference to `__cxa_pure_virtual'
/tmp/ccU22FxL.o:(.eh_frame+0x39f): undefined reference to `__gxx_personality_v0'
collect2: error: ld returned 1 exit status
make: *** [all] Error 1
##########################################################################

**Comment by jonnings** [comment]
Hi, nicky179854.

Are all of the error messages about undefined references to tclap?
What type of system/computer are you compiling on? Mac or linux? 
What version of boost are you using (see version.hpp in the boost directory)?

Also, I think it would be helpful if you attach the entire error message and the exact Makefile that you are using.

**Comment by nicky179854** [comment]
I've attached the entire output from the make command as well as the Makefile.

I am running this on a bio-linux, however I also have access to a Mac and linux if I need to switch the machine I'm working on. 

The version of boost that I'm using is 1.48.0.2

[nohup.out.txt](https://github.com/Chrom3D/Chrom3D/files/1506214/nohup.out.txt)

[Makefile.txt](https://github.com/Chrom3D/Chrom3D/files/1506219/Makefile.txt)

**Comment by jonnings** [comment]
Hi, again nicky179854. Your boost library is quite old. Chrom3D requires boost version >=1.54. I would start by upgrading boost, and then try to compile again. If you still are unable to compile, it might be worthwhile to try to install on another machine. Let me know if this works.

**Comment by nicky179854** [comment]
This seems to have worked! Thank you. Also, I saw in another thread that you guys were going to post some kind of pipeline on how to generate a gtrack file from a HiC matrix file. Has that been uploaded somewhere on github?

**Comment by jonnings** [comment]
Good to hear that it worked. A pipeline for generating the GTrack file will be up in a few days, yes.
