### ISSUE TITLE
Problem in installation

### ISSUE THREAD

**Issue by smarhon** [Chrom3D/Chrom3D#4]
Hi
I have following problem when I try to install Chrom3D even though boost is installed. Do you have any advice?

/tmp/ccJk6Jlx.o: In function `main':
Chrom3D.cpp:(.text.startup+0x750): undefined reference to `boost::filesystem::detail::create_directory(boost::filesystem::path const&, boost::system::error_code*)'
/tmp/ccJk6Jlx.o: In function `_GLOBAL__sub_I__Z14parseArgumentsiPPc':
Chrom3D.cpp:(.text.startup+0xc23): undefined reference to `boost::system::generic_category()'
Chrom3D.cpp:(.text.startup+0xc2f): undefined reference to `boost::system::generic_category()'
Chrom3D.cpp:(.text.startup+0xc3b): undefined reference to `boost::system::system_category()'
collect2: error: ld returned 1 exit status
make: *** [all] Error 1

Thanks
Sajid

**Comment by jonnings** [comment]
Hi.
Which version of boost are you using?

**Comment by smarhon** [comment]
It shows:

1.54.0.1ubuntu1

**Comment by jonnings** [comment]
Ok. I suggest that you update to a more recent boost version and try again.

**Comment by smarhon** [comment]
Hi

I updated the packages and 1.54.0.1ubuntu1 is the latest version that can be installed on Ubuntu.
I downloaded the latest version manually and set the include directory in the Chom3D makefile but it problem is still. 

BTW, I installed Chrom3D on mac and it worked without any problem because I think it doesn't need boost. But I really need it on a Ubuntu machine.

**Comment by jonnings** [comment]
Compilation with Boost version 1.54.0.1ubuntu1 should now work.
