### ISSUE TITLE
Install err

### ISSUE THREAD

**Issue by seqyuan** [Chrom3D/Chrom3D#6]
Hi

    I have following problem when I try to install Chrom3D. Do you have any advice?
在包含自 src/Chrom3D.cpp：19 的文件中:
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:27:29: 错误：tclap/SwitchArg.h：没有那个文件或目录
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:28:34: 错误：tclap/MultiSwitchArg.h：没有那个文件或目录
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:29:37: 错误：tclap/UnlabeledValueArg.h：没有那个文件或目录
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:30:37: 错误：tclap/UnlabeledMultiArg.h：没有那个文件或目录
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:32:30: 错误：tclap/XorHandler.h：没有那个文件或目录
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:33:31: 错误：tclap/HelpVisitor.h：没有那个文件或目录
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:34:34: 错误：tclap/VersionVisitor.h：没有那个文件或目录
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:35:37: 错误：tclap/IgnoreRestVisitor.h：没有那个文件或目录
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:37:33: 错误：tclap/CmdLineOutput.h：没有那个文件或目录
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:38:29: 错误：tclap/StdOutput.h：没有那个文件或目录
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:40:30: 错误：tclap/Constraint.h：没有那个文件或目录
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:41:36: 错误：tclap/ValuesConstraint.h：没有那个文件或目录
In file included from src/Chrom3D.cpp:19:
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:71: 错误：expected class-name before ‘{’ token
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:78: 错误：‘Arg’在此作用域中尚未声明
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:78: 错误：模板参数 1 无效
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:78: 错误：模板参数 2 无效
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:111: 错误：‘XorHandler’没有命名一个类型
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:118: 错误：‘Arg’在此作用域中尚未声明
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:118: 错误：模板参数 1 无效
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:118: 错误：模板参数 2 无效
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:125: 错误：‘Visitor’在此作用域中尚未声明
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:125: 错误：模板参数 1 无效
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:125: 错误：模板参数 2 无效
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:130: 错误：ISO C++ 不允许声明无类型的‘CmdLineOutput’
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:130: 错误：expected ‘;’ before ‘*’ token
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:153: 错误：‘Arg’未声明
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:158: 错误：‘Visitor’未声明
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:158: 错误：‘void TCLAP::CmdLine::deleteOnExit(int*)’无法被重载
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:153: 错误：与‘void TCLAP::CmdLine::deleteOnExit(int*)’
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:214: 错误：‘Arg’未声明
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:220: 错误：‘Arg’未声明
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:228: 错误：‘Arg’未声明
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:228: 错误：‘Arg’未声明
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:235: 错误：‘Arg’在此作用域中尚未声明
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:235: 错误：模板参数 1 无效
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:235: 错误：模板参数 2 无效
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:254: 错误：ISO C++ 不允许声明无类型的‘CmdLineOutput’
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:254: 错误：expected ‘;’ before ‘*’ token
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:259: 错误：‘CmdLineOutput’未声明
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:274: 错误：‘Arg’在此作用域中尚未声明
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:274: 错误：模板参数 1 无效
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:274: 错误：模板参数 2 无效
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:279: 错误：ISO C++ 不允许声明无类型的‘XorHandler’
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:279: 错误：expected ‘;’ before ‘&’ token
src/../src/tclap-1.2.1/include/tclap/CmdLine.h: In constructor ‘TCLAP::CmdLine::CmdLine(const std::string&, char, const std::string&, bool)’:
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:328: 错误：‘Arg’在此作用域中尚未声明
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:328: 错误：模板参数 1 无效
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:328: 错误：模板参数 2 无效
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:334: 错误：类‘TCLAP::CmdLine’没有名为‘_xorHandler’的字段
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:334: 错误：‘XorHandler’在此作用域中尚未声明
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:335: 错误：‘Arg’不能出现在常量表达式中
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:335: 错误：模板参数 1 无效
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:335: 错误：模板参数 2 无效
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:336: 错误：‘Visitor’在此作用域中尚未声明
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:336: 错误：模板参数 1 无效
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:336: 错误：模板参数 2 无效
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:337: 错误：类‘TCLAP::CmdLine’没有名为‘_output’的字段
src/../src/tclap-1.2.1/include/tclap/CmdLine.h: In destructor ‘virtual TCLAP::CmdLine::~CmdLine()’:
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:351: 错误：‘_output’在此作用域中尚未声明
src/../src/tclap-1.2.1/include/tclap/CmdLine.h: In member function ‘void TCLAP::CmdLine::_constructor()’:
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:358: 错误：‘_output’在此作用域中尚未声明
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:358: 错误：expected type-specifier before ‘StdOutput’
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:358: 错误：expected ‘;’ before ‘StdOutput’
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:360: 错误：‘Arg’未声明
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:362: 错误：‘Visitor’在此作用域中尚未声明
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:362: 错误：‘v’在此作用域中尚未声明
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:366: 错误：expected type-specifier before ‘HelpVisitor’
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:366: 错误：expected ‘;’ before ‘HelpVisitor’
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:367: 错误：‘SwitchArg’在此作用域中尚未声明
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:367: 错误：‘help’在此作用域中尚未声明
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:367: 错误：expected type-specifier before ‘SwitchArg’
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:367: 错误：expected ‘;’ before ‘SwitchArg’
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:374: 错误：expected type-specifier before ‘VersionVisitor’
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:374: 错误：expected ‘;’ before ‘VersionVisitor’
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:375: 错误：‘vers’在此作用域中尚未声明
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:375: 错误：expected type-specifier before ‘SwitchArg’
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:375: 错误：expected ‘;’ before ‘SwitchArg’
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:383: 错误：expected type-specifier before ‘IgnoreRestVisitor’
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:383: 错误：expected ‘;’ before ‘IgnoreRestVisitor’
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:384: 错误：‘SwitchArg’在此作用域中尚未声明
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:384: 错误：‘ignore’在此作用域中尚未声明
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:384: 错误：expected type-specifier before ‘SwitchArg’
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:384: 错误：expected ‘;’ before ‘SwitchArg’
src/../src/tclap-1.2.1/include/tclap/CmdLine.h: At global scope:
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:393: 错误：‘Arg’在此作用域中尚未声明
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:393: 错误：模板参数 1 无效
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:393: 错误：模板参数 2 无效
src/../src/tclap-1.2.1/include/tclap/CmdLine.h: In member function ‘void TCLAP::CmdLine::xorAdd(int&)’:
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:395: 错误：‘_xorHandler’在此作用域中尚未声明
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:397: 错误：‘ArgVectorIterator’在此作用域中尚未声明
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:397: 错误：expected ‘;’ before ‘it’
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:397: 错误：‘it’在此作用域中尚未声明
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:397: 错误：对成员‘end’的请求出现在‘ors’中，而后者具有非类类型‘int’
src/../src/tclap-1.2.1/include/tclap/CmdLine.h: At global scope:
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:405: 错误：变量或字段‘xorAdd’声明为 void
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:405: 错误：‘Arg’在此作用域中尚未声明
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:405: 错误：‘a’在此作用域中尚未声明
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:405: 错误：‘Arg’在此作用域中尚未声明
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:405: 错误：‘b’在此作用域中尚未声明
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:413: 错误：变量或字段‘add’声明为 void
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:413: 错误：‘Arg’在此作用域中尚未声明
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:413: 错误：‘a’在此作用域中尚未声明
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:418: 错误：变量或字段‘add’声明为 void
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:418: 错误：‘Arg’在此作用域中尚未声明
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:418: 错误：‘a’在此作用域中尚未声明
src/../src/tclap-1.2.1/include/tclap/CmdLine.h: In member function ‘void TCLAP::CmdLine::parse(std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&)’:
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:458: 错误：‘ArgListIterator’在此作用域中尚未声明
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:458: 错误：expected ‘;’ before ‘it’
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:459: 错误：‘it’在此作用域中尚未声明
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:459: 错误：对成员‘end’的请求出现在‘((TCLAP::CmdLine*)this)->TCLAP::CmdLine::_argList’中，而后者具有非类类型‘int’
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:462: 错误：‘_xorHandler’在此作用域中尚未声明
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:473: 错误：‘Arg’未声明
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:476: 错误：‘CmdLineParseException’在此作用域中尚未声明
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:483: 错误：‘CmdLineParseException’在此作用域中尚未声明
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:485: 错误：expected type-specifier before ‘ArgException’
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:485: 错误：expected ‘)’ before ‘&’ token
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:485: 错误：expected ‘{’ before ‘&’ token
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:485: 错误：‘e’在此作用域中尚未声明
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:485: 错误：expected ‘;’ before ‘)’ token
src/Chrom3D.cpp:242: 错误：expected ‘}’ at end of input
src/Chrom3D.cpp: At global scope:
src/Chrom3D.cpp:242: 错误：expected ‘}’ at end of input
In file included from src/Chrom3D.cpp:19:
src/../src/tclap-1.2.1/include/tclap/CmdLine.h: In function ‘void TCLAP::ClearContainer(C&) [with C = int]’:
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:347:   instantiated from here
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:60: 错误：‘int’不是类、结构或联合类型
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:61: 错误：对成员‘begin’的请求出现在‘c’中，而后者具有非类类型‘int’
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:61: 错误：对成员‘end’的请求出现在‘c’中，而后者具有非类类型‘int’
src/../src/tclap-1.2.1/include/tclap/CmdLine.h:62: 错误：对成员‘clear’的请求出现在‘c’中，而后者具有非类类型‘int’
make: *** [all] 错误 1
cat: .: 是一个目录

Thanks
Zan Yuan

**Comment by tharvesh** [comment]
Hi Zan Yuan,

Could you please copy and paste your Makefile? 

Cheers

**Comment by seqyuan** [comment]
@tharvesh 

my Makefile is:
```
CFLAGS = -O3
SRCPATH=src
TCLAPINCLUDE=src/tclap-1.2.1/include
all:
	g++ -O3 -I /installpath/boost_1_57_0/include/boost $(TCLAPINCLUDE) $(SRCPATH)/Util.cpp $(SRCPATH)/Bead.cpp $(SRCPATH)/Chromosome.cpp $(SRCPATH)/Randomizer.cpp $(SRCPATH)/Constraint.cpp $(SRCPATH)/Model.cpp $(SRCPATH)/MCMC.cpp $(SRCPATH)/Chrom3D.cpp -o Chrom3D
```


I solved this problem by edit Makefile like this:
```
CFLAGS = -O3
SRCPATH=src
TCLAPINCLUDE=src/tclap-1.2.1/include

all:
	g++ -O3 -I $(TCLAPINCLUDE) $(SRCPATH)/Util.cpp $(SRCPATH)/Bead.cpp $(SRCPATH)/Chromosome.cpp $(SRCPATH)/Randomizer.cpp $(SRCPATH)/Constraint.cpp $(SRCPATH)/Model.cpp $(SRCPATH)/MCMC.cpp $(SRCPATH)/Chrom3D.cpp -o Chrom3D
```

and then run this command 
```
cd Chrom3D-master/src/tclap-1.2.1/include && ln -s /installpath/boost_1_57_0/include/boost boost
```


thank you very much

**Comment by tharvesh** [comment]
Hi Zan,

The error in your makefile is that you have missed the `-I` before including tclap library. It should be 

`g++ -O3 -I /installpath/boost_1_57_0/include/boost -I $(TCLAPINCLUDE) $(SRCPATH)/Util.cpp $(SRCPATH)/Bead.cpp $(SRCPATH)/Chromosome.cpp $(SRCPATH)/Randomizer.cpp $(SRCPATH)/Constraint.cpp $(SRCPATH)/Model.cpp $(SRCPATH)/MCMC.cpp $(SRCPATH)/Chrom3D.cpp -o Chrom3D`

Cheers
